local p = require("oldworld.palette")

return {
    markdownH1 = { fg = p.purple, bold = true },
    markdownH2 = { fg = p.blue, bold = true },
    markdownH3 = { fg = p.green, bold = true },
    markdownH4 = { fg = p.yellow, bold = true },
    markdownH5 = { fg = p.red, bold = true },
    markdownH6 = { fg = p.magenta, bold = true },
    markdownHeadingDelimiter = { fg = p.subtext4 },
    markdownHeadingRule = { fg = p.subtext4 },
    markdownId = { fg = p.red },
    markdownIdDeclaration = { fg = p.purple },
    markdownIdDelimiter = { fg = p.red },
    markdownLinkDelimiter = { fg = p.subtext4 },
    markdownLinkText = { fg = p.purple, italic = true },
    markdownListMarker = { fg = p.subtext4 },
    markdownOrderedListMarker = { fg = p.subtext4 },
    markdownRule = { fg = p.subtext4 },
    markdownUrl = { fg = p.green, bg = p.none },
    markdownBlockquote = { fg = p.fg },
    markdownBold = { fg = p.fg, bg = p.none, bold = true },
    markdownItalic = { fg = p.fg, bg = p.none, italic = true },
    markdownCode = { fg = p.yellow },
    markdownCodeBlock = { fg = p.yellow },
    markdownCodeDelimiter = { fg = p.subtext4 },
    RenderMarkdownCode = { bg = p.gray1 },
    RenderMarkdownCodeInline = { fg = p.bright_green, bold = true },
    RenderMarkdownBullet = { fg = p.cyan },
    RenderMarkdownH1Bg = { bg = p.dark_purple, fg = p.bright_purple },
    RenderMarkdownH2Bg = { bg = p.dark_blue, fg = p.bright_blue },
    RenderMarkdownH3Bg = { bg = p.dark_green, fg = p.bright_green },
    RenderMarkdownH4Bg = { bg = p.dark_yellow, fg = p.bright_yellow },
    RenderMarkdownH5Bg = { bg = p.dark_red, fg = p.bright_red },
    RenderMarkdownH6Bg = { bg = p.dark_magenta, fg = p.bright_magenta },
    RenderMarkdownH1 = { bg = p.dark_purple, fg = p.bright_purple },
    RenderMarkdownH2 = { bg = p.dark_blue, fg = p.bright_blue },
    RenderMarkdownH3 = { bg = p.dark_green, fg = p.bright_green },
    RenderMarkdownH4 = { bg = p.dark_yellow, fg = p.bright_yellow },
    RenderMarkdownH5 = { bg = p.dark_red, fg = p.bright_red },
    RenderMarkdownH6 = { bg = p.dark_magenta, fg = p.bright_magenta },
    RenderMarkdownTableHead = { fg = p.subtext3 },
    RenderMarkdownTableRow = { fg = p.subtext3 },
}
